### ISSUE TITLE
How to use load_dataset() by local dataset?

### ISSUE THREAD

**Issue by guobabaya** [juice500ml/xlm_to_xlsr#4]
Hello,in the _common_voice_process method, because my server has no network, I cannot use load_dataset to download the dataset online.For example common_voice_georgian, I manually downloaded ka.tar.gz which contains tsv and mp3 files. I don't know how to use them by load_dataset(). Could you please give me some advice or guidance？Looking forward to your reply, thank you.

**Comment by juice500ml** [comment]
I think you can approach in either two ways:
1. Inside the computer where the internet is enabled, download the common_voice dataset using the huggingface's `datasets.load_dataset` with [`cache_dir` set](https://github.com/juice500ml/xlm_to_xlsr/blob/2a0caff/data_utils.py#L30). Then copy the downloaded files inside cache directory (of the internet-enabled computer) to your server's cache directory. (Highly recommended)
2. [Fix the tsv files](https://github.com/juice500ml/xlm_to_xlsr/blob/2a0caff0cd5d51b102476ea926f90197d13acd56/create_mls_csv.py) to accomodate [`load_dataset`'s API](https://github.com/juice500ml/xlm_to_xlsr/blob/2a0caff/data_utils.py#L40-L45).

**Comment by guobabaya** [comment]
Thanks for your reply, I will try again.

**Comment by guobabaya** [comment]
Excuse me, I still haven't solved the problem.I don't have a server that can be downloaded online. Can I trouble you to upload the dataset about ka (file of MP3 is not needed, I just want to observe its structure) for subsequent offline download. I'm really sorry to bother you like this, thank you.

**Comment by juice500ml** [comment]
Huggingface datasets are stored in Apache arrow format. It won't be easy to transform the raw dataset downloaded from CommonVoice homepage to huggingface datasets-friendly format.

```
/data/dataset/public/huggingface_datasets/common_voice/el/6.1.0/f7a9d973839b7706e9e281c19b7e512f31badf3c0fdbd21c671f3c4bf9acf3b9
❯❯❯ ls
cache-03260f036d8f8550.arrow  cache-543c70d9a34a54d3.arrow  cache-bf0503aa47014cfe.arrow    common_voice-train.arrow
cache-29755082a04363f1.arrow  cache-74f277a2665ac3d0.arrow  cache-c877d966202bb822.arrow    common_voice-validation.arrow
cache-3b6cad32ab84fb05.arrow  cache-80f70e767190d986.arrow  common_voice-invalidated.arrow  dataset_info.json
cache-4249427b5cbb230d.arrow  cache-9e73302b23032d3f.arrow  common_voice-other.arrow        LICENSE
cache-4e923f1658086de4.arrow  cache-aad5004f5698d353.arrow  common_voice-test.arrow
```

**Comment by guobabaya** [comment]
Ok，thanks for your help, i will try again.
