### ISSUE TITLE
Questions about training resources

### ISSUE THREAD

**Issue by guobabaya** [juice500ml/xlm_to_xlsr#5]
Hi, first of all thanks for your help, I have solved the problem with the dataset. My device has only one gpu, I modified per_device_train_batch_size=24 in V1.yaml, but the result shows RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.95 GiB total capacity; 3.33 GiB already allocated; 16.31 MiB free; 3.35 GiB reserved in total by PyTorch). I followed the online suggestion and changed per_device_train_batch_size to 1, but the same error still occurs. Is there a solution without replacing the device? I look forward to your reply.

**Comment by juice500ml** [comment]
It seems that your GPU size is not big enough.
You can set `gradient_accumulation_steps` and `gradient_checkpointing` for `TrainingArguments (config/train/v1.yaml)` while training to train on a small GPU.
For more info, check https://huggingface.co/docs/transformers/perf_train_gpu_one

Note that, with different batch sizes, the results will be different to the reported performances (as it will influence training).

**Comment by guobabaya** [comment]
Thank you very much，i will try again.
